# Rust formatting configuration
# Using only stable features to avoid warnings

edition = "2021"
max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
merge_derives = true