//! Service implementations for webserver
//!
//! This module contains the real implementations of all webserver traits.
//! Mock implementations are automatically generated by mockall in the test environment.

pub mod file_manager;
pub mod client_broadcaster;
pub mod ipc_communicator;
pub mod client_registry;
pub mod metrics_aggregator;

// Service-specific tests
#[cfg(test)]
pub mod tests;

// Re-export all service implementations
pub use file_manager::RealFileManager;
pub use client_broadcaster::RealClientBroadcaster;
pub use ipc_communicator::RealIpcCommunicator;
pub use client_registry::RealClientRegistry;
pub use metrics_aggregator::RealMetricsAggregator;