//! Production service implementations
//!
//! This module contains the real implementations of all orchestrator traits.
//! Mock implementations are automatically generated by mockall in the test environment.

pub mod api_keys;
pub mod ipc_communicator;
pub mod file_manager;
pub mod process_manager;
pub mod optimizer;

// Service-specific tests
#[cfg(test)]
pub mod tests;

// Re-export all service implementations
pub use api_keys::RealApiKeySource;
pub use ipc_communicator::RealIpcCommunicator;
pub use file_manager::RealFileSystem;
pub use process_manager::RealProcessManager;
pub use optimizer::RealOptimizer;